# Generated by Django 3.0.9 on 2020-08-05 14:12

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('confirmed', models.BooleanField()),
                ('confidence_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('class_id', models.TextField()),
                ('surface', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('end_x', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('end_y', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_x', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_y', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image')),
            ],
        ),
    ]
